[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION",
  "RUSTFLAGS"
]

[target.riscv64gc-unknown-linux-gnu]
pre-build = ["DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq --no-install-recommends cmake"]
